### ISSUE TITLE
Demo?

### ISSUE THREAD

**Issue by everyplace** [guardian/workflow-frontend#23]
Dear Guardian development team,

A few years ago (I suspect maybe in the Fall of 2015), a few of my colleagues from News UK and I were at your office and saw a demo of this tool in action. While it is wonderful to see then, it has come to my attention that NYT (my current employer) is open to exploring tools like Workflow, but I cannot find anything public about it, other than this repo. Do you have any demos of it around, or a more robust readme?

Sincerely,
Erin Sparling

**Comment by blishen** [comment]
Hi Erin,

We're happy to arrange a demo of Workflow in production.
Drop me a mail, and we can pick up this discussion there. 
Cheers,

David Blishen

(mail is first.last@theguardian.com)
